
PRINT 'CREATING SQL ERROR TABLE'

CREATE TABLE [dbo].[SqlErrors](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ErrorTime] [datetime] NULL,
    [ERROR_NUMBER] [int] NULL,
    [ERROR_SEVERITY] [int] NULL,
    [ERROR_PROCEDURE] [nvarchar](126) NULL,
    [ERROR_LINE] [int] NULL,
    [ERROR_STATE] [int] NULL,
    [ERROR_MESSAGE] [nvarchar](2048) NULL,
 CONSTRAINT [PK_SqlErrors] PRIMARY KEY CLUSTERED
(
    [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
